export function renderFaucetHome(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>PowerChain Devnet Faucet</title>
<meta name="description" content="PowerChain native SOL and tPWRC devnet faucet service." />
<style>
:root{color-scheme:dark;--bg:#07100b;--panel:#0d1711;--line:#203228;--text:#edf7f0;--muted:#8fa198;--green:#29d982}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 70% -15%,rgba(41,217,130,.2),transparent 42%),var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,sans-serif}.shell{width:min(1120px,calc(100% - 32px));margin:auto;padding:32px 0 80px}header{display:flex;justify-content:space-between;align-items:center;padding:16px 0}.brand{font-weight:850;letter-spacing:.08em}.status{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:.85rem}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(41,217,130,.12)}main{padding-top:10vh}.eyebrow{color:var(--green);font-size:.72rem;font-weight:850;letter-spacing:.14em;text-transform:uppercase}h1{max-width:850px;margin:14px 0 18px;font-size:clamp(3rem,8vw,7rem);line-height:.9;letter-spacing:-.065em}p{max-width:690px;color:var(--muted);line-height:1.7}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:48px}.card{min-height:230px;padding:24px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018));box-shadow:0 32px 90px rgba(0,0,0,.24)}.card h2{margin:46px 0 10px;font-size:1.7rem}.card a{display:inline-flex;margin-top:14px;color:var(--green);font-weight:750}code{color:#79e9ac;font-family:ui-monospace,SFMono-Regular,monospace}.notice{margin-top:22px;padding:18px;border:1px solid var(--line);border-radius:16px;color:var(--muted);font-size:.85rem}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding-top:50px}}
</style>
</head>
<body><div class="shell"><header><div class="brand">POWERCHAIN</div><div class="status"><span class="dot"></span>Devnet service</div></header><main><span class="eyebrow">Standalone faucet application</span><h1>Test SOL and tPWRC, with explicit policy boundaries.</h1><p>The faucet service is isolated under <code>apps/faucet</code>. Native SOL requests use Solana devnet airdrops; tPWRC remains disabled until its Token-2022 devnet mint is configured and verified.</p><section class="grid"><article class="card"><span class="eyebrow">Health</span><h2>Service readiness</h2><p>Inspect cluster and service availability without caching.</p><a href="/api/v1/health">Open health →</a></article><article class="card"><span class="eyebrow">Standard</span><h2>Faucet policy</h2><p>Review exact units, limits, assets, and devnet-only restrictions.</p><a href="/standard/">Open standard →</a></article><article class="card"><span class="eyebrow">API v1</span><h2>Route catalog</h2><p>Discover the bounded faucet validation API and supported routes.</p><a href="/api/v1">Open API →</a></article></section><div class="notice">No mainnet funds, treasury keys, or arbitrary transaction execution are exposed by this service.</div></main></div></body></html>`;
}
