[package]
name = "powerchain-powerpay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "PowerPay settlement reference program for SOL, USDC and approved PowerChain assets"
license.workspace = true
publish.workspace = true

[lib]
name = "powerchain_powerpay"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = []
program = ["dep:pinocchio", "dep:pinocchio-log", "dep:pinocchio-token-2022"]
mainnet-beta = ["program"]

[dependencies]
pinocchio = { workspace = true, optional = true }
pinocchio-log = { workspace = true, optional = true }
pinocchio-token-2022 = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
