#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerPayError {
    InvalidInstruction = 1,
    InvalidAccount = 2,
    MissingSignature = 3,
    AccountNotWritable = 4,
    Unauthorized = 5,
    InvalidAmount = 6,
    UnsupportedAsset = 7,
    InvalidMint = 8,
    InvalidTokenProgram = 9,
    InvalidDecimals = 10,
    InvalidRate = 11,
    StaleRate = 12,
    SlippageExceeded = 13,
    ArithmeticOverflow = 14,
    PaymentAlreadyExists = 15,
    PaymentNotFound = 16,
    InvalidStatusTransition = 17,
    SettlementExpired = 18,
    ReplayDetected = 19,
    ProgramPaused = 20,
    AlreadyInitialized = 21,
    NotInitialized = 22,
    InvalidAuthority = 23,
    InvalidTreasury = 24,
    InvalidFee = 25,
    RefundExceedsSettledAmount = 26,
    InstructionTooLarge = 27,
    UnsupportedInstructionVersion = 28,
    TrailingInstructionData = 29,
    InvalidAccountOwner = 30,
    PaymentIdMismatch = 31,
    InvalidTimestamp = 32,
}

impl PowerPayError {
    pub const fn code(self) -> u32 { self as u32 }

    pub const fn message(self) -> &'static str {
        match self {
            Self::InvalidInstruction => "invalid instruction",
            Self::InvalidAccount => "invalid account",
            Self::MissingSignature => "missing required signature",
            Self::AccountNotWritable => "account is not writable",
            Self::Unauthorized => "unauthorized authority",
            Self::InvalidAmount => "amount must be positive",
            Self::UnsupportedAsset => "asset is not approved",
            Self::InvalidMint => "mint does not match the approved asset",
            Self::InvalidTokenProgram => "token program is invalid",
            Self::InvalidDecimals => "asset decimals are invalid",
            Self::InvalidRate => "rate is invalid",
            Self::StaleRate => "rate observation is stale",
            Self::SlippageExceeded => "quote slippage limit exceeded",
            Self::ArithmeticOverflow => "arithmetic overflow",
            Self::PaymentAlreadyExists => "payment already exists",
            Self::PaymentNotFound => "payment not found",
            Self::InvalidStatusTransition => "invalid payment status transition",
            Self::SettlementExpired => "settlement window expired",
            Self::ReplayDetected => "replayed request",
            Self::ProgramPaused => "program is paused",
            Self::AlreadyInitialized => "program state is already initialized",
            Self::NotInitialized => "program state is not initialized",
            Self::InvalidAuthority => "authority is invalid",
            Self::InvalidTreasury => "treasury is invalid",
            Self::InvalidFee => "service fee is invalid",
            Self::RefundExceedsSettledAmount => "refund exceeds refundable amount",
            Self::InstructionTooLarge => "instruction data exceeds the supported limit",
            Self::UnsupportedInstructionVersion => "unsupported instruction version",
            Self::TrailingInstructionData => "instruction contains trailing data",
            Self::InvalidAccountOwner => "account owner is invalid",
            Self::PaymentIdMismatch => "payment identifier does not match",
            Self::InvalidTimestamp => "timestamp is invalid",
        }
    }
}
